name: ci-test-go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-fmt:
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME: ${{ matrix.runtime }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        runtime: ["docker", "containerd", "crio"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "v1.20"

      - name: Check gofmt
        run: make gofmt
        working-directory: KubeArmor

  go-lint:
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME: ${{ matrix.runtime }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        runtime: ["docker", "containerd", "crio"]
        
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "v1.20"

      - name: Run Revive Action on KubeArmor
        uses: morphy2k/revive-action@v2
        with:
          path: "./KubeArmor/..."

  go-lint-tests:
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME: ${{ matrix.runtime }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        runtime: ["docker", "containerd", "crio"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "v1.20"

      - name: Run Revive Action on KubeArmor tests
        uses: morphy2k/revive-action@v2
        with:
          path: "./tests/..."

  go-sec:
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME: ${{ matrix.runtime }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        runtime: ["docker", "containerd", "crio"]
        
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "v1.20"

      - name: Run Gosec Security Scanner
        run: make gosec
        working-directory: KubeArmor

  go-test:
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME: ${{ matrix.runtime }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        runtime: ["docker", "containerd", "crio"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "v1.20"

      - name: Run go test on the KubeArmor/KubeArmor directory
        run: go test ./...
        working-directory: KubeArmor

  license:
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME: ${{ matrix.runtime }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        runtime: ["docker", "containerd", "crio"]
    steps:
      - uses: actions/checkout@v3

      - name: Check License Header
        uses: apache/skywalking-eyes@9bd5feb86b5817aa6072b008f9866a2c3bbc8587
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
